### ISSUE TITLE
ТЗ 

### ISSUE THREAD

**Issue by chopppstix** [chopppstix/Project_Kursach#1]
1. Общие сведения:
Цель: Создание сервиса по поиску музыкальных обложек, позволяющего пользователям легко и быстро находить и скачивать обложки для своей музыкальной коллекции.

2. Назначение и цели создания (развития) системы:
Создание сервиса, который обеспечит пользователей доступом к обширной базе данных музыкальных обложек и предоставит возможность удобного поиска, выбора и скачивания обложек для аудиофайлов.

3. Характеристика объектов автоматизации:
- Система должна поддерживать различные форматы аудиофайлов, включая MP3, FLAC, WAV и т. д.
- Должна быть организована интеграция с базой данных музыкальных обложек для обеспечения доступа к обширной коллекции обложек.
- Веб-сервис должен быть доступен для использования из различных устройств, включая компьютеры, смартфоны и планшеты.

4. Требования к системе:
- Сервис должен обеспечивать высокую скорость поиска обложек и отзывчивость интерфейса.
- Система должна быть доступна 24/7 без значительных перерывов на техническое обслуживание.
- Должна быть реализована функция автоматического обновления базы данных обложек и их сопоставления с аудиофайлами пользователя.

5. Состав и содержание работ по созданию системы:
- Разработка дизайна и пользовательского интерфейса веб-сервиса.
- Создание базы данных музыкальных обложек и их интеграция с сервисом.
- Реализация алгоритмов поиска и сопоставления обложек с аудиофайлами.
- Тестирование и отладка сервиса.
- Развертывание и настройка сервиса на серверной инфраструктуре.

6. Порядок контроля и приемки системы:
- Организация тестирования непосредственно разработчиками.
- Проведение вычислительных и функциональных тестов для проверки производительности и корректного функционирования сервиса.
- Внедрение системы в рабочую среду и проверка ее работоспособности с участием заказчика.

7. Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие:
- Импорт и сопоставление базы данных аудиофайлов и обложек.
- Проведение необходимых настроек и конфигураций для работы сервиса на конкретной серверной инфраструктуре.

8. Требования к документированию:
- Создание технической документации, описывающей архитектуру и функционал системы, а также процедуры по ее настройке и эксплуатации.
- Разработка руководства пользователя, объясняющего использование сервиса и функционал его интерфейса.

9. Источники разработки:
- Нормативные акты, стандарты и рекомендации, связанные с созданием и использованием веб-сервисов.
- Документация разработчиков конкретных баз данных музыкальных обложек и платформы развертывания.

**Comment by wldmr-key** [comment]
назначение - для кого предназначен сервис
цель - почему за это заплатят
объекты автоматизации - то, что существует и без твоей системы, а ты описываешь свои функции
А функциональных требований у тебя нет - мне непонятно, что принимать в результате

**Comment by chopppstix** [comment]
Общие сведения
Название проекта: Сервис для поиска музыкальных обложек.
Заказчик проекта: КФ МГТУ им. Н. Э. Баумана
Разработчик: Студент КФ МГТУ им. Н.Э. Баумана группы ИУК5-51Б Серпинский Р.Э.

Цели и назначения создания системы
Цели: создать сервис, который поможет музыканту с выбором или созданием обложки, а дизайнеру найти клиентов.

Характеристика объектов автоматизации
• Должна быть организована интеграция с базой данных музыкальных обложек для обеспечения доступа к обширной коллекции обложек.
 • Планируется сделать веб-сервис доступный для использования различных устройств.

Требования к системе
• Функция регистрации и авторизации пользователей.
• Функция поиска обложек по фильтрам.

Состав и содержание работ по созданию системы
Этапы разработки:
• Анализ требований.
• Проектирование приложения.
• Создание базы данных музыкальных обложек и их интеграция с сервисом.
• Запуск и демонстрация.

Порядок контроля и приемки системы
• Контроль и приемка будут осуществляться на каждом этапе разработки согласно утвержденному плану контроля и приемки. 
• Внедрение системы в рабочую среду и проверка ее работоспособности

Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие
• В контексте курсовой работы подготовка объекта автоматизации не требуется, так как сайт будет создан и использоваться исключительно в учебных целях.

Требования к документированию
Документация к курсовой работе включает в себя:
◦ Техническое задание.
◦ Диаграммы проектирования.
◦ Отчет о выполненных работах.

Источники разработки
• Литературные и онлайн-ресурсы, учебные материалы, образцы кода из учебной программы и другие источники информации, использованные при разработке.

**Comment by wldmr-key** [comment]
определись с назначением, целью, характеристикой и функциями

**Comment by chopppstix** [comment]
Назначение сервис предназначен для дизайнеров и музыкантов.
Цель: 
Предназначен для коммерческого использования, обеспечить продажи обложек дизайнеров за определенную процентную ставку. Характеристика объектов автоматизации
 ◦ Объекты автоматизации включают:
 ▪ Базу данных с изображением.
 ▪ Пользовательский интерфейс для запросов и получения информации. ребования к системе
1. Функциональные требования:
 ▪ Разработка базы данных с обложками.
 ▪ Создание интерфейса для запросов к базе данных.
2. Нефункциональные требования:
 ▪ Интуитивно понятный интерфейс.
 ▪ Безопасное хранение данных пользователей.
 ▪ Высокая доступность сервиса.

**Comment by wldmr-key** [comment]
Объекты автоматизации - это то, что существует без твоей системы и ты это автоматизируешь. В твоем случае это - ?

Функция - это то, что несет предсказуемый и полезный результат. У тебя это не так

**Comment by chopppstix** [comment]
Автоматизация 

1) Регистрация и аутентификация пользователей: объект автоматизации должен предоставлять возможность регистрации новых пользователей и аутентификации существующих.

2) Поиск и фильтрация изображений: объект автоматизации должен иметь функциональность поиска и фильтрации обложек по различным параметрам (тегам).

3) Загрузка и хранение изображений: объект автоматизации должен позволять пользователям загружать и хранить свои изображения.

4) Объект автоматизации должен предоставлять возможность покупки и продажи обложек.

Функциональные требования: 
1) Добавление в корзину: пользователи должны иметь возможность добавлять выбранные обложки в корзину для последующей покупки.

2) Оформление заказа: после добавления обложек в корзину, пользователь должен иметь возможность оформить заказ, указав необходимую информацию.

3) Загрузка приобретенных обложек: после успешного завершения покупки, пользователи должны иметь возможность загрузить приобретенные обложки на свое устройство.

4) Управление заказами и историей: пользователи должны иметь возможность просматривать свои заказы, историю покупок и отслеживать состояние доставки.

**Comment by wldmr-key** [comment]
опять все сам ))

объектом автоматизации является процесс взаимодействия между дизайнерами обложек и потенциальными покупателями

функции - приемлемо
