### ISSUE TITLE
Предметная область

### ISSUE THREAD

**Issue by chopppstix** [chopppstix/Project_Kursach#4]
Описание предметной области: 
Хорошая обложка — одно из средств продвижения: она повышает узнаваемость и продажи артиста. Поэтому важно, чтобы дизайн соответствовал этим целям. Например, можно делать отсылки к обложкам ранее выпущенных треков или оставлять пасхалки для уже существующей аудитории. Суть в том, чтобы вызвать интерес и повысить цитируемость. Идея – крупная база данных с музыкальными обложками. Обложки бывают разных видов (стилистики): рисованные, 3D, коллажи, пластилиновые. Также каждая работа имеет свою цену, в зависимости от сложности и личногобренда дизайнера. Личный бренд – это неотъемлемая часть для успешного роста, позволяющая выйти на новый уровень. Привлекая к себе все больше аудитории и увеличивая ценность своим работам. Большое количество дизайнеров тратят очень много времени и ресурсов на поиск заказчиков. Для этого они пишут артистам в личные сообщения в соц. сетях, отмечают в историях, предлагая свои услуги. Найти клиента сложно, так же, как и заказчики со своей стороны испытывает трудности в поиске хорошей обложки. Как заказать работу? Для начала нужно пройти регистрацию, ввести логин и пароль. Есть два вида данной регистрации: 

*  Личный кабинет заказчика, через который он может производить заказы. 
*  Вторая, аккаунт дизайнера, где он может выкладывать свои работы и принимать заказы. 

У каждого аккаунта есть свой рейтинг, который может понизить, если не соблюдать правила площадки. Данный рейтинг присутствует, как у «продавца», так и «покупателя»  Музыкант может приобрести готовую работу сразу в один клик, либо связаться с дизайнером, который сможет воплотить в жизнь его идеи. Для этого должен быть личный чат. В данном чате будет присутствовать бот, который поможет составить грамотное ТЗ (техническое задание), а далее уже выходит на связь сам дизайнер.  И заказчик связывается с дизайнером на прямую, далее они обсуждают и корректируют ТЗ, для этого нужно расписать свои мысли максимально подробно, от цветовой гаммы до расположения предметов на «холсте». Дизайнер может сделать определенное количество правок, далее за каждую правку придется доплачивать.

**Comment by wldmr-key** [comment]
нет пояснения, откуда берется рейтинг

появляется ли ТЗ в виде отдельного документа или им является содержимое чата?

кем определяется количество бесплатных правок?

расчеты проходят мимо системы?

**Comment by chopppstix** [comment]
Рейтинг уберу, так как не придумал, как его буду реализовывать. 
Да верно, ТЗ будет являться содержимое чата.
Количество правок определяет сам дизайнер, так как у каждого свой подход.
Про расчеты еще думаю.
