### ISSUE TITLE
Прототип пользовательского интерфейса

### ISSUE THREAD

**Issue by chopppstix** [chopppstix/Project_Kursach#6]
![image](https://github.com/chopppstix/Project_Kursach/assets/94444045/313c55f7-e4a3-4636-aa32-b5476ad4ade6)

**Comment by wldmr-key** [comment]
хорошо, но мало

**Comment by chopppstix** [comment]
Вопрос, у меня тут зеленная кнопка "купить". Можно ли её сделать просто для вида? Или если у меня есть эта кнопка, то тогда должен быть весь процесс оплаты? 

![image](https://github.com/chopppstix/Project_Kursach/assets/94444045/920176ff-46a4-476f-9fe0-26ba44bdb98f)
![image](https://github.com/chopppstix/Project_Kursach/assets/94444045/59e829b9-68aa-4034-a89b-c0fe8ba91ba5)

**Comment by chopppstix** [comment]
Еще добавлю корзину

**Comment by wldmr-key** [comment]
скажу пока ок, хотя все это больше про дизайн, а не функционал / модель данных

**Comment by wldmr-key** [comment]
хотя... у тебя ж система, вроде, не должна давать прямых покупок. Контрагенты будут долго и мучительно договариваться об условиях контракта. Или я что-то не выкупаю?

**Comment by chopppstix** [comment]
Могут быть прямые покупки уже готовых работ, а также осуществить под заказ работу.

**Comment by wldmr-key** [comment]
что-то не увидел этого в описании предметной области

**Comment by chopppstix** [comment]
Я писал, что клиент может купить в один клик готовую работу, либо заказать
