### ISSUE TITLE
Предварительный анализ аналогов

### ISSUE THREAD

**Issue by chopppstix** [chopppstix/Project_Kursach#7]
В данной сфере аналогов не существует. В общих чертах схожа с любым сервисом по продаже чего либо.

**Comment by wldmr-key** [comment]
обрати внимание на сайты, продающие дизайн

**Comment by chopppstix** [comment]
Я провел анализ и выявил, что прямыми конкурентами в моей сфере (музыкальных обложек) являются группы в соц. сетях. 
1) Данные группы не удобны, их много и не всегда можно найти нужное сообщество. 
2) В этих группах встречается большое количество ненужной информации и рекламы, что усложняет комфортный подбор обложки.

Также конкурентами будут являться фриланс биржи, однако очень малая часть музыкантов прибегают к биржам, так как это не удобно и долго. Количество дизайнеров, которые используют подобные сервисы, крайне мала. Поэтому клиенту также будет трудно найти подходящую работу.

Таким образом, проанализировал данные сервисы и группы в соц. сетях. Я заметил, что на данный момент музыканты могут заказать обложку у дизайнера разными способами. Однако все эти способы не удобны и занимают много времени для поиска.

**Comment by wldmr-key** [comment]
Все верно, но крайне желательно расширить описание иллюстрациями и отзывами

**Comment by chopppstix** [comment]
Проведен анализ и выявлено, что прямыми конкурентами в моей сфере (музыкальных обложек) являются группы в соц. сетях.

Данные группы не удобны, их много и не всегда можно найти нужное сообщество, особенно когда нет на примете конкретного дизайнера, который тебе нравится. Так как в соц сетях у каждого дизайнера свой никнейм. И редко кто указывает в названии ключевые слова, такие как "дизайн", "обложки"... (скриншот 2)
В этих группах встречается большое количество ненужной информации и рекламы, что усложняет комфортный подбор обложки. (скриншот 3) 
Также конкурентами будут являться фриланс биржи, однако очень малая часть музыкантов прибегают к биржам, так как это не удобно и основаная масса заказчиков не пользуются такими платформами. (скриншот 4) Большим минусом является то, что многие фриланс биржи ушли из России, а бирж которые работают в СНГ не так много. (скриншот 5) Так же количество дизайнеров, которые используют подобные сервисы, крайне мала. Поэтому клиенту будет трудно найти подходящую работу для своего трека.  Также чтобы подкрепить свои высказывания, создал голосование среди дизайнеров. Задав им вопрос: «Пользовались ли они когда-нибудь фриланс биржами, для продажи обложек?»  (Скриншот 6)

Провел анализ, данные сервисы и группы в соц. сетях. На данный момент музыканты могут заказать обложку у дизайнера разными способами. Однако все эти способы не удобны и занимают много времени для поиска, как с одной стороны, так и с другой. 

<img width="552" alt="скриншот1" src="https://github.com/chopppstix/Project_Kursach/assets/94444045/e1ccabd5-663e-4366-bb2c-c7eabe1e9594">
<img width="562" alt="скриншот2" src="https://github.com/chopppstix/Project_Kursach/assets/94444045/b6601b37-1075-4900-a69a-58af4824c8f4">
<img width="580" alt="скриншот3" src="https://github.com/chopppstix/Project_Kursach/assets/94444045/62c5b273-68e3-4a3e-b09b-f6ee1c994d2d">
<img width="1290" alt="скриншот4" src="https://github.com/chopppstix/Project_Kursach/assets/94444045/e723934d-fdc5-439d-8892-61d7ab1029a7">
<img width="1103" alt="скриншот5" src="https://github.com/chopppstix/Project_Kursach/assets/94444045/2893d481-6893-47b2-91f8-34b53cb74ec5">
![image](https://github.com/chopppstix/Project_Kursach/assets/94444045/0c843b74-4f8b-459e-b913-c744d63db408)

**Comment by wldmr-key** [comment]
все хорошо, но убери первое лицо из РПЗ

**Comment by chopppstix** [comment]
Убрал первое лицо
