### ISSUE TITLE
Требования к системе

### ISSUE THREAD

**Issue by chopppstix** [chopppstix/Project_Kursach#8]
* Регистрация и аутентификация пользователей (Присутствует две регистрации: покупатель и продавец) 
* Поиск обложек осуществляется через каталог либо через поисковую строку с использованием тегов.
* Импорт данных из баз данных. 

_В дальнейших реализациях: _

* Оплата работ. 
* Хранение истории покупок пользователя, для обращения к нужным отчетам в удобное время. Точно такая же отчетность будет у продавца по продаже товара. 
* Модерация, осуществляющая контроль и обработку, выкладываемых работ перед публикацией.

**Comment by wldmr-key** [comment]
> Импорт данных из баз данных. 

что имеется в виду?

**Comment by chopppstix** [comment]
(Только скорее всего это будет реализовано позже)
База данных изображений:
   - Хранение и управление базой данных с информацией о доступных изображениях.
   - Возможность добавления, удаления и редактирования изображений в базе данных.
   - Категоризация изображений по различным параметрам, таким как тема, стиль, цена и др.

Также после покупки, товар будет отправляться в корзину.

**Comment by wldmr-key** [comment]
не стоит упоминать святые слова всуе ))

почему бы вместо базы данных не употреблять то, чем является набор изображений на самом деле (портфолио, образцы и т.д.)

**Comment by chopppstix** [comment]
Если простым языком,то функция добавления обложек
